### ISSUE TITLE
Homey insights give false info

### ISSUE THREAD

**Issue by matrover** [gruijter/com.gruijter.enelogic#1]
Hi Robin,

i love the app, but im getting some strange results in the insights view (the spikes): 
![image](https://user-images.githubusercontent.com/18408057/27432928-a81b1b8e-5752-11e7-951a-ef7e6f396c0c.png)

im using (the not supported) LS-110 with firmware 1.3.4-EL and the enelogic app v1.0.6 

the enelogic cloud doenst show these spikes: 
![image](https://user-images.githubusercontent.com/18408057/27432996-f0453994-5752-11e7-8d4d-799b75046b4e.png)

could you maybe look into this? the Youless homey app shows the same behavior. 

Thanks in advance. 

Marijn

**Comment by gruijter** [comment]
Might be that sometimes the comma is missing and the value is read as x1000. But I'm not sure. I don't have a ls110 myself so it is difficult for me to test. If you can open your router and port-forward to the youless I could analyze remotely. Drop me an email (gruijter at hotmail dot com) or find me on slack (gruijter)

**Comment by gruijter** [comment]
By the way. In the youless app I added support for the LS110. I'm using a different driver for that then the ls120. Did you try that app/driver?

**Comment by matrover** [comment]
Thanks for looking into this! ive sended you an email. 
i've tried the Youless app, gives me the same result.

**Comment by rnldnkp** [comment]
Same problem here. It seems it skips some characters. Did you find out what the problem was?

Like 2749,09 becomes 249,09 / 274,09 / 749,09. Have seen them all

Strange thing is, it only happens with P1 readings effecting only the meter readings (4x) and sum of meters. S0 meter and both live usage is not affected as far as I can see.

If we can't find what's wrong, maybe you could compare the last reading and check for strange fluctuations so you can ignore those?

**Comment by matrover** [comment]
The problem was an too high firmware version of my youless, ik had an firmware for LS120 installed in my LS110

**Comment by gruijter** [comment]
@rnldnkp My app simply uses what it receives from the Youless device.

As matrover stated his issue was caused by faulty firmware in the youless. Do you have the right and lastest firmware installed in your device? (I guess you do, otherwise you wouldn't be able to use S0, I think).
It could also be caused by a faulty wire between the youless and your smartmeter. Try replacing that cable.

I actually already have some simple filtering implemented to ignore unrealistic values, but not for the complex situation you describe where the decimal point gets shifted. So my advise is to find the root-cause of your problem, and that is somewhere in your meter cabinet.

**Comment by rnldnkp** [comment]
FYI, as some time has passed.

I created a simple powershell script to dump all raw data from youless to a logfile. In these logs I can see the string contains false date at least once a hour. So your app really logs what it gets :)

Besides that, I contacted Youless with the same question I posted here. And currently we try to figure out what could be wrong (I send them the log file as well).

Youless pointed out I have a DSRM2 meter (without CRC), and as you suggested, the cable might have an issue. Do have some spare RJ11 cables (and connectors), could try some.

Next it got me thinking, a 35A meter can only pass on 8050 watt a hour right? That's 22,4 watt in 10 seconds if I'm correct. So two pulses should be no further then 22,4 watt from each other. Might be something Youless or your app can recognize?

For now I keep the log running and just gave Youless an update, will keep you posted.

**Comment by gruijter** [comment]
Thanks for giving the update! I looked into your suggestion on filtering based on maximum power usage. I think this is something that youless could integrate in their firmware. But when I do a next app update I will try to put it in if its not too much work. But it is not as simple as you suggest because of  number of scenarios that could happen. Eg, what if at app startup the incoming value is wrong. The app would need to figure out what is the correct value without introducing a delay in measurements. Also, the max power used with smartmeters is 55,2 kW (3x80A), so the app needs to keep all readings in that can theoretically go from -60kW (production) to +60kW (use) within 10 seconds.

**Comment by gruijter** [comment]
@rnldnkp @matrover New version 1.1.2 is on github. It does a number of sanity checks in an attempt to filter out corrupted data from the youless. Let me know if it works!

Robin

**Comment by gruijter** [comment]
After extensive contact with Youless I found out that Youless is aware of the corrupted data. They also found a solution that will be implemented in the next firmware of the ls120 (1.4.1). I tested a beta version of that firmware, and it is indeed solved 🤗

In the new app version 2.0.0 I still included an option to do filtering on the app level. So you can use that untill Youless releases the new firmware.

**Comment by rnldnkp** [comment]
@gruijter as mentioned was working with youless to find the problem (logging data besides homey for days in a row) and then testing the firmware. Forgot to update you guys. Didn't know you had the same problem yourself btw ;)

My youless is running 1.4.1 beta 3 for about 8-9 days now. Have to test for a longer period of time since we already accomplished to reduce the problem from 20 times a day, and then once a day to once in 4-5 days (for each meter) in a previous beta. Youless did a great job here, even releasing new firmware just after the holidays.

If all readings are fine for like 15 days, I'm sure the problem is fixed 👍 
So far, so good!

Next up, getting this on Athoms sprint: https://github.com/athombv/homey/issues/2084
